// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Belt_MapString from "rescript/lib/es6/belt_MapString.js";

function concat(prim0, prim1) {
  return prim0.concat(prim1);
}

function length(prim) {
  return prim.length;
}

function empty(a) {
  return a.length === 0;
}

function filter(prim0, prim1) {
  return prim0.filter(Curry.__1(prim1));
}

function flatMap(a, fn) {
  return Belt_Array.concatMany(a.map(Curry.__1(fn)));
}

function flatMapWithIndex(a, fn) {
  return Belt_Array.concatMany(Belt_Array.mapWithIndex(a, fn));
}

function from(prim) {
  return Array.from(prim);
}

function includes(prim0, prim1) {
  return prim0.includes(prim1);
}

function join(prim0, prim1) {
  return prim0.join(prim1);
}

function map(prim0, prim1) {
  return prim0.map(Curry.__1(prim1));
}

function reduce(prim0, prim1, prim2) {
  return prim0.reduce(Curry.__2(prim1), prim2);
}

function sort(prim0, prim1) {
  return prim0.sort(Curry.__2(prim1));
}

function some(prim0, prim1) {
  return prim0.some(Curry.__1(prim1));
}

function indexOf(prim0, prim1) {
  return prim0.indexOf(prim1);
}

function find(prim0, prim1) {
  return Caml_option.undefined_to_opt(prim0.find(Curry.__1(prim1)));
}

function uniq(a) {
  return reduce(a, (function (a, i) {
                if (a.includes(i)) {
                  return a;
                } else {
                  return a.concat([i]);
                }
              }), []);
}

function groupBy(a, fn) {
  return Belt_MapString.toArray(reduce(a, (function (m, v) {
                    var a = Belt_MapString.get(m, Curry._1(fn, v));
                    return Belt_MapString.set(m, Curry._1(fn, v), a !== undefined ? a.concat([v]) : [v]);
                  }), undefined));
}

var flat = Belt_Array.concatMany;

var mapWithIndex = Belt_Array.mapWithIndex;

var slice = Belt_Array.slice;

export {
  concat ,
  length ,
  empty ,
  filter ,
  flat ,
  flatMap ,
  mapWithIndex ,
  flatMapWithIndex ,
  from ,
  includes ,
  join ,
  map ,
  reduce ,
  slice ,
  sort ,
  some ,
  indexOf ,
  find ,
  uniq ,
  groupBy ,
  
}
/* No side effect */
