// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Console$Std from "./Console.js";

function print(val) {
  Console$Std.log(val);
  return val;
}

export {
  print ,
  
}
/* No side effect */
