// Generated by ReScript, PLEASE EDIT WITH CARE


function getError(env) {
  var val = Deno.env.get(env);
  if (val == null) {
    return {
            TAG: /* Error */1,
            _0: env + " not defined"
          };
  } else {
    return {
            TAG: /* Ok */0,
            _0: val
          };
  }
}

export {
  getError ,
  
}
/* No side effect */
