// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Array$Std from "./Array.js";

function empty(prim) {
  return {};
}

function to(key, val) {
  return Js_dict.fromArray([[
                key,
                val
              ]]);
}

function concat(d1, d2) {
  return Js_dict.fromArray(Array$Std.concat(Js_dict.entries(d1), Js_dict.entries(d2)));
}

function map(d, fn) {
  return Js_dict.fromArray(Array$Std.map(Js_dict.entries(d), fn));
}

function flatten(d) {
  return Js_dict.fromArray(Array$Std.flatMap(d, Js_dict.entries));
}

function flatMap(d, fn) {
  return Js_dict.fromArray(Array$Std.map(Array$Std.flatMap(d, Js_dict.entries), fn));
}

var toArray = Js_dict.entries;

var fromArray = Js_dict.fromArray;

var get = Js_dict.get;

export {
  empty ,
  toArray ,
  fromArray ,
  to ,
  get ,
  concat ,
  map ,
  flatten ,
  flatMap ,
  
}
/* No side effect */
