// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Int from "rescript/lib/es6/belt_Int.js";

function toString(prim) {
  return String(prim);
}

var fromString = Belt_Int.fromString;

export {
  toString ,
  fromString ,
  
}
/* No side effect */
