// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Array$Std from "./Array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function toResult(o, err) {
  if (o !== undefined) {
    return {
            TAG: /* Ok */0,
            _0: Caml_option.valFromOption(o)
          };
  } else {
    return {
            TAG: /* Error */1,
            _0: err
          };
  }
}

function flatten(o) {
  if (o === undefined) {
    return ;
  }
  var o$1 = Caml_option.valFromOption(o);
  if (o$1 !== undefined) {
    return Caml_option.some(Caml_option.valFromOption(o$1));
  }
  
}

function seq(a) {
  return Array$Std.reduce(a, (function (a, e) {
                if (a !== undefined && e !== undefined) {
                  return Array$Std.concat(a, [Caml_option.valFromOption(e)]);
                }
                
              }), []);
}

function seq2(param) {
  var a2 = param[1];
  var a1 = param[0];
  if (a1 !== undefined && a2 !== undefined) {
    return [
            Caml_option.valFromOption(a1),
            Caml_option.valFromOption(a2)
          ];
  }
  
}

function seq3(param) {
  var a3 = param[2];
  var a2 = param[1];
  var a1 = param[0];
  if (a1 !== undefined && a2 !== undefined && a3 !== undefined) {
    return [
            Caml_option.valFromOption(a1),
            Caml_option.valFromOption(a2),
            Caml_option.valFromOption(a3)
          ];
  }
  
}

function seq4(param) {
  var a4 = param[3];
  var a3 = param[2];
  var a2 = param[1];
  var a1 = param[0];
  if (a1 !== undefined && a2 !== undefined && a3 !== undefined && a4 !== undefined) {
    return [
            Caml_option.valFromOption(a1),
            Caml_option.valFromOption(a2),
            Caml_option.valFromOption(a3),
            Caml_option.valFromOption(a4)
          ];
  }
  
}

var map = Belt_Option.map;

var flatMap = Belt_Option.flatMap;

export {
  toResult ,
  map ,
  flatMap ,
  flatten ,
  seq ,
  seq2 ,
  seq3 ,
  seq4 ,
  
}
/* No side effect */
