// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";

function includes(prim0, prim1) {
  return prim0.includes(prim1);
}

function startsWith(prim0, prim1) {
  return prim0.startsWith(prim1);
}

function endsWith(prim0, prim1) {
  return prim0.endsWith(prim1);
}

function slice(prim0, prim1, prim2) {
  return prim0.slice(prim1, prim2);
}

function sliceToEnd(prim0, prim1) {
  return prim0.slice(prim1);
}

function split(prim0, prim1) {
  return prim0.split(prim1);
}

function trim(prim) {
  return prim.trim();
}

function sub(s, start, end) {
  return s.slice(start, end);
}

function match(prim0, prim1) {
  return Caml_option.null_to_opt(prim0.match(prim1));
}

function repeat(prim0, prim1) {
  return prim0.repeat(prim1);
}

export {
  includes ,
  startsWith ,
  endsWith ,
  slice ,
  sliceToEnd ,
  split ,
  trim ,
  sub ,
  match ,
  repeat ,
  
}
/* No side effect */
