// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "fs";

function read(path) {
  if (Fs.existsSync(path)) {
    return {
            TAG: /* Ok */0,
            _0: Deno.readTextFileSync(path)
          };
  } else {
    return {
            TAG: /* Error */1,
            _0: path + " does not exist"
          };
  }
}

function write(data, path) {
  Deno.writeFileSync(path, data);
  
}

export {
  read ,
  write ,
  
}
/* fs Not a pure module */
