// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Array$Std from "../Array.js";

function read(path) {
  return Array$Std.from(Deno.readDirSync(path));
}

export {
  read ,
  
}
/* No side effect */
